const imageFolder = 'images'; // Folder where your assets are stored
const totalImages = 80; // Total number of items
const imageGrid = document.getElementById('imageGrid');
const lightbox = document.getElementById('lightbox');
const closeLightbox = document.getElementById('closeLightbox');

const videoIndices = new Set([57, 73]);
const gifIndices = new Set([11, 14, 70]);

// Serve the WebP/AVIF derivatives generated by scripts/optimize-images.sh. Set to
// false to fall back to the original full-resolution PNG/GIF assets.
const USE_OPTIMIZED_ASSETS = true;

// Responsive thumbnail widths emitted by the optimizer (must match THUMB_WIDTHS).
const THUMB_WIDTHS = [400, 800];
// `sizes` hint: grid cells are ~150-400px wide depending on viewport.
const GRID_SIZES = '(max-width: 600px) 50vw, 200px';

// Incremental rendering: build the grid in batches so a large collection doesn't
// create thousands of DOM nodes up-front. A sentinel below the grid pulls in the
// next batch as the user scrolls.
const BATCH_SIZE = 24;
// How many of the very first images load eagerly (above the fold).
const EAGER_LOAD_COUNT = 8;

let nextIndex = 1;

function classify(i) {
    const isVideo = videoIndices.has(i);
    const isGif = gifIndices.has(i);
    const extension = isVideo ? 'png' : isGif ? 'gif' : 'png';
    return { isVideo, isGif, extension };
}

function makeImg(i, eager) {
    const img = document.createElement('img');
    img.alt = `Image ${i}`;
    img.loading = eager ? 'eager' : 'lazy';
    img.decoding = 'async';
    img.fetchPriority = eager ? 'high' : 'low';
    img.width = 400; // Explicit dimensions reserve layout space (reduces CLS)
    img.height = 400;
    img.classList.add('grid-item');
    return img;
}

function srcsetFor(i, format) {
    return THUMB_WIDTHS.map((w) => `${imageFolder}/thumbs/${i}-${w}.${format} ${w}w`).join(', ');
}

// Build a grid cell for item `i`.
function buildGridItem(i) {
    const { isVideo, isGif, extension } = classify(i);
    const eager = i <= EAGER_LOAD_COUNT;

    const gridItem = document.createElement('div');
    if (isVideo) {
        gridItem.classList.add('video-container');
    }

    let clickTarget;

    if (USE_OPTIMIZED_ASSETS && !isGif) {
        // Still image: responsive AVIF + WebP via <picture>.
        const picture = document.createElement('picture');
        for (const format of ['avif', 'webp']) {
            const source = document.createElement('source');
            source.type = `image/${format}`;
            source.srcset = srcsetFor(i, format);
            source.sizes = GRID_SIZES;
            picture.appendChild(source);
        }
        const img = makeImg(i, eager);
        img.src = `${imageFolder}/thumbs/${i}-800.webp`; // fallback for the <picture>
        picture.appendChild(img);
        gridItem.appendChild(picture);
        clickTarget = picture;
    } else {
        // Animated GIF (single animated WebP) or unoptimized fallback.
        const img = makeImg(i, eager);
        img.src = USE_OPTIMIZED_ASSETS
            ? `${imageFolder}/thumbs/${i}.webp`
            : `${imageFolder}/${i}.${extension}`;
        gridItem.appendChild(img);
        clickTarget = img;
    }

    if (isVideo) {
        const overlay = document.createElement('div');
        overlay.classList.add('overlay');
        const playIcon = document.createElement('span');
        playIcon.classList.add('play-icon');
        playIcon.textContent = '▶';
        overlay.appendChild(playIcon);
        gridItem.appendChild(overlay);
    }

    clickTarget.addEventListener('click', () => {
        openLightbox(i, isVideo ? 'mp4' : extension);
    });

    return gridItem;
}

// Render the next batch of items into a DocumentFragment (single reflow per batch).
function renderNextBatch() {
    if (nextIndex > totalImages) return false;
    const fragment = document.createDocumentFragment();
    const end = Math.min(nextIndex + BATCH_SIZE - 1, totalImages);
    for (; nextIndex <= end; nextIndex++) {
        fragment.appendChild(buildGridItem(nextIndex));
    }
    imageGrid.appendChild(fragment);
    return nextIndex <= totalImages;
}

// Initial batch, then lazily reveal the rest via an IntersectionObserver sentinel.
(function initGrid() {
    renderNextBatch();
    if (nextIndex > totalImages) return; // everything fit in the first batch

    const sentinel = document.createElement('div');
    sentinel.id = 'gridSentinel';
    sentinel.setAttribute('aria-hidden', 'true');
    imageGrid.insertAdjacentElement('afterend', sentinel);

    if (!('IntersectionObserver' in window)) {
        // No IO support: render everything at once.
        while (renderNextBatch()) {}
        sentinel.remove();
        return;
    }

    const TRIGGER_MARGIN = 600; // keep this many px below the viewport populated

    // Render batches until the grid is exhausted or the sentinel drops below the
    // trigger zone. Rendering only one batch per intersection stalls the grid:
    // appending a batch keeps the (still-nearby) sentinel continuously
    // intersecting, so the observer never fires a second time. Filling until the
    // sentinel leaves the zone guarantees forward progress on every callback.
    const fill = () => {
        let guard = 0;
        while (nextIndex <= totalImages) {
            const viewportH = window.innerHeight || document.documentElement.clientHeight || 0;
            // getBoundingClientRect forces a reflow, so this reflects batches just
            // appended (heights are reserved via width/height + aspect-ratio).
            if (sentinel.getBoundingClientRect().top > viewportH + TRIGGER_MARGIN) break;
            renderNextBatch();
            if (++guard > totalImages) break; // safety against runaway loops
        }
        if (nextIndex > totalImages) {
            observer.disconnect();
            sentinel.remove();
        }
    };

    const observer = new IntersectionObserver((entries) => {
        if (entries.some((entry) => entry.isIntersecting)) fill();
    }, { rootMargin: `${TRIGGER_MARGIN}px 0px` });
    observer.observe(sentinel);
})();

function openLightbox(index, extension) {
    // Remove previous content (if any) in the lightbox
    const existingContent = lightbox.querySelector('.lightbox-content');
    if (existingContent) {
        existingContent.remove();
    }

    // Create a new content container for the lightbox
    const contentContainer = document.createElement('div');
    contentContainer.classList.add('lightbox-content');
    lightbox.appendChild(contentContainer);

    // Create a container for media and overlay
    const mediaContainer = document.createElement('div');
    mediaContainer.classList.add('lightbox-media');
    contentContainer.appendChild(mediaContainer);

    // Fetch metadata (cached so re-opening the same item avoids a network round-trip)
    fetchMetadata(index)
        .then((data) => {
            // Add overlay title
            const titleOverlay = document.createElement('div');
            titleOverlay.textContent = data.name || 'No Title';
            titleOverlay.classList.add('lightbox-overlay', 'lightbox-title-overlay');
            mediaContainer.appendChild(titleOverlay);

            // Add overlay description
            if (data.description && data.description.trim()) {
                const descriptionOverlay = document.createElement('div');
                descriptionOverlay.innerHTML = parseMarkdown(data.description); // Use parseMarkdown for formatting
                descriptionOverlay.classList.add('lightbox-overlay', 'lightbox-description-overlay');
                mediaContainer.appendChild(descriptionOverlay);
            }
        })
        .catch((error) => {
            console.error(`Error fetching metadata for ${index}:`, error);

            // Fallback title overlay
            const titleOverlay = document.createElement('div');
            titleOverlay.textContent = 'No Title';
            titleOverlay.classList.add('lightbox-overlay', 'lightbox-title-overlay');
            mediaContainer.appendChild(titleOverlay);
    });


    // Handle video
    if (extension === 'mp4') {
        const videoElement = document.createElement('video');
        videoElement.src = USE_OPTIMIZED_ASSETS
            ? `${imageFolder}/full/${index}.mp4`
            : `${imageFolder}/${index}.mp4`;
        videoElement.controls = true;
        videoElement.autoplay = true;
        videoElement.preload = 'metadata'; // Don't prefetch the whole clip until it plays
        videoElement.style.maxWidth = '100%';
        videoElement.style.maxHeight = '90vh';
        videoElement.style.objectFit = 'contain';
        mediaContainer.appendChild(videoElement);
    } else if (USE_OPTIMIZED_ASSETS && !gifIndices.has(index)) {
        // Still image: AVIF + WebP via <picture>.
        const picture = document.createElement('picture');
        for (const format of ['avif', 'webp']) {
            const source = document.createElement('source');
            source.type = `image/${format}`;
            source.srcset = `${imageFolder}/full/${index}.${format}`;
            picture.appendChild(source);
        }
        const imgElement = document.createElement('img');
        imgElement.src = `${imageFolder}/full/${index}.webp`;
        imgElement.alt = '';
        imgElement.decoding = 'async';
        imgElement.style.maxWidth = '100%';
        imgElement.style.maxHeight = '90vh';
        imgElement.style.objectFit = 'contain';
        picture.appendChild(imgElement);
        mediaContainer.appendChild(picture);
    } else {
        // Animated GIF (animated WebP) or unoptimized fallback image.
        const imgElement = document.createElement('img');
        imgElement.src = USE_OPTIMIZED_ASSETS
            ? `${imageFolder}/full/${index}.webp`
            : `${imageFolder}/${index}.${extension}`;
        imgElement.alt = ''; // No alt text for lightbox images
        imgElement.decoding = 'async';
        imgElement.style.maxWidth = '100%';
        imgElement.style.maxHeight = '90vh';
        imgElement.style.objectFit = 'contain';
        mediaContainer.appendChild(imgElement);
    }

    lightbox.style.display = 'flex';
}

// Close the lightbox when the close button is clicked
closeLightbox.addEventListener('click', closeLightboxHandler);

// Close the lightbox when clicking outside the content
lightbox.addEventListener('click', (e) => {
    if (e.target === lightbox) {
        closeLightboxHandler();
    }
});

function closeLightboxHandler() {
    lightbox.style.display = 'none';
    const videoElement = lightbox.querySelector('video');
    if (videoElement) {
        videoElement.pause(); // Pause the video
        videoElement.currentTime = 0; // Reset playback to the start
    }
}

// Cache metadata responses so repeated lightbox opens don't refetch the same JSON.
const metadataCache = new Map();
function fetchMetadata(index) {
    if (metadataCache.has(index)) {
        return metadataCache.get(index);
    }
    const request = fetch(`metadata/${index}.json`).then((response) => {
        if (!response.ok) {
            throw new Error(`HTTP ${response.status}`);
        }
        return response.json();
    });
    metadataCache.set(index, request);
    // Don't cache failures permanently — allow a retry on the next open.
    request.catch(() => metadataCache.delete(index));
    return request;
}

// Function to parse basic Markdown
function parseMarkdown(markdown) {
    if (!markdown) return '';
    // Replace \n with <br> for line breaks
    let html = markdown.replace(/\\n/g, '<br>');
    // Convert Markdown links [text](url) to <a> tags
    html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>');
    return html;
}
