const imageFolder = 'images'; // Folder where your assets are stored
const totalImages = 80; // Total number of items
const imageGrid = document.getElementById('imageGrid');
const lightbox = document.getElementById('lightbox');
const closeLightbox = document.getElementById('closeLightbox');

const videoIndices = new Set([57, 73]);
const gifIndices = new Set([11, 14, 70]);

// Serve the lightweight WebP derivatives generated by scripts/optimize-images.sh
// (images/thumbs/*.webp in the grid, images/full/*.webp + re-encoded MP4s in the
// lightbox). Set back to false to fall back to the original full-resolution assets.
const USE_OPTIMIZED_ASSETS = true;

// How many of the first images to load eagerly (above-the-fold); the rest stay lazy.
const EAGER_LOAD_COUNT = 8;

// Resolve the grid (thumbnail) source for a given item.
function gridSrc(i, extension) {
    if (USE_OPTIMIZED_ASSETS) {
        return `${imageFolder}/thumbs/${i}.webp`;
    }
    return `${imageFolder}/${i}.${extension}`;
}

// Build the whole grid off-DOM, then attach once. Appending each item directly to
// the live grid forces the browser to recalculate layout up to 80 times; a single
// DocumentFragment insertion triggers just one reflow.
const fragment = document.createDocumentFragment();

for (let i = 1; i <= totalImages; i++) {
    const isVideo = videoIndices.has(i);
    const extension = isVideo ? 'png' : gifIndices.has(i) ? 'gif' : 'png';

    const gridItem = document.createElement('div');
    if (isVideo) {
        gridItem.classList.add('video-container'); // Add a container for overlay
    }

    const element = document.createElement('img');
    element.src = gridSrc(i, extension); // Set the image source
    element.alt = `Image ${i}`; // Set the alt text (for accessibility)
    // Eager-load the first row so the page paints quickly; lazy-load the rest.
    element.loading = i <= EAGER_LOAD_COUNT ? 'eager' : 'lazy';
    element.decoding = 'async'; // Avoid blocking the main thread while decoding
    element.fetchPriority = i <= EAGER_LOAD_COUNT ? 'high' : 'low';
    element.width = 400; // Explicit dimensions reserve layout space (reduces CLS)
    element.height = 400;
    element.classList.add('grid-item'); // Optional: Add a class for styling

    if (isVideo) {
        // Add the overlay and play icon for video placeholders
        const overlay = document.createElement('div');
        overlay.classList.add('overlay');
        const playIcon = document.createElement('span');
        playIcon.classList.add('play-icon');
        playIcon.textContent = '▶'; // Play icon (you can use an icon library for better visuals)
        overlay.appendChild(playIcon);
        gridItem.appendChild(overlay);
    }

    // Add click event to open the lightbox
    element.addEventListener('click', () => {
        openLightbox(i, isVideo ? 'mp4' : extension);
    });

    // Append the image to the grid container (with overlay if video)
    gridItem.appendChild(element);
    fragment.appendChild(gridItem);
}

imageGrid.appendChild(fragment);

function openLightbox(index, extension) {
    // Remove previous content (if any) in the lightbox
    const existingContent = lightbox.querySelector('.lightbox-content');
    if (existingContent) {
        existingContent.remove();
    }

    // Create a new content container for the lightbox
    const contentContainer = document.createElement('div');
    contentContainer.classList.add('lightbox-content');
    lightbox.appendChild(contentContainer);

    // Create a container for media and overlay
    const mediaContainer = document.createElement('div');
    mediaContainer.classList.add('lightbox-media');
    contentContainer.appendChild(mediaContainer);

    // Fetch metadata (cached so re-opening the same item avoids a network round-trip)
    fetchMetadata(index)
        .then((data) => {
            // Add overlay title
            const titleOverlay = document.createElement('div');
            titleOverlay.textContent = data.name || 'No Title';
            titleOverlay.classList.add('lightbox-overlay', 'lightbox-title-overlay');
            mediaContainer.appendChild(titleOverlay);

            // Add overlay description
            if (data.description && data.description.trim()) {
                const descriptionOverlay = document.createElement('div');
                descriptionOverlay.innerHTML = parseMarkdown(data.description); // Use parseMarkdown for formatting
                descriptionOverlay.classList.add('lightbox-overlay', 'lightbox-description-overlay');
                mediaContainer.appendChild(descriptionOverlay);
            }
        })
        .catch((error) => {
            console.error(`Error fetching metadata for ${index}:`, error);

            // Fallback title overlay
            const titleOverlay = document.createElement('div');
            titleOverlay.textContent = 'No Title';
            titleOverlay.classList.add('lightbox-overlay', 'lightbox-title-overlay');
            mediaContainer.appendChild(titleOverlay);
    });


    // Handle video
    if (extension === 'mp4') {
        const videoElement = document.createElement('video');
        videoElement.src = USE_OPTIMIZED_ASSETS
            ? `${imageFolder}/full/${index}.mp4`
            : `${imageFolder}/${index}.mp4`;
        videoElement.controls = true;
        videoElement.autoplay = true;
        videoElement.preload = 'metadata'; // Don't prefetch the whole clip until it plays
        videoElement.style.maxWidth = '100%';
        videoElement.style.maxHeight = '90vh';
        videoElement.style.objectFit = 'contain';
        mediaContainer.appendChild(videoElement);
    } else {
        // Handle image
        const imgElement = document.createElement('img');
        imgElement.src = USE_OPTIMIZED_ASSETS
            ? `${imageFolder}/full/${index}.webp`
            : `${imageFolder}/${index}.${extension}`;
        imgElement.alt = ''; // No alt text for lightbox images
        imgElement.decoding = 'async';
        imgElement.style.maxWidth = '100%';
        imgElement.style.maxHeight = '90vh';
        imgElement.style.objectFit = 'contain';
        mediaContainer.appendChild(imgElement);
    }

    lightbox.style.display = 'flex';
}

// Close the lightbox when the close button is clicked
closeLightbox.addEventListener('click', closeLightboxHandler);

// Close the lightbox when clicking outside the content
lightbox.addEventListener('click', (e) => {
    if (e.target === lightbox) {
        closeLightboxHandler();
    }
});

function closeLightboxHandler() {
    lightbox.style.display = 'none';
    const videoElement = lightbox.querySelector('video');
    if (videoElement) {
        videoElement.pause(); // Pause the video
        videoElement.currentTime = 0; // Reset playback to the start
    }
}

// Cache metadata responses so repeated lightbox opens don't refetch the same JSON.
const metadataCache = new Map();
function fetchMetadata(index) {
    if (metadataCache.has(index)) {
        return metadataCache.get(index);
    }
    const request = fetch(`metadata/${index}.json`).then((response) => {
        if (!response.ok) {
            throw new Error(`HTTP ${response.status}`);
        }
        return response.json();
    });
    metadataCache.set(index, request);
    // Don't cache failures permanently — allow a retry on the next open.
    request.catch(() => metadataCache.delete(index));
    return request;
}

// Function to parse basic Markdown
function parseMarkdown(markdown) {
    if (!markdown) return '';
    // Replace \n with <br> for line breaks
    let html = markdown.replace(/\\n/g, '<br>');
    // Convert Markdown links [text](url) to <a> tags
    html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>');
    return html;
}
